import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import { FlatCompat } from '@eslint/eslintrc';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});
export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'dist/**',
      'next-env.d.ts',
      // Vendored dependencies and generated output — not our code, and linting them buried the
      // 400-odd real findings under 3,751 errors from files nobody here wrote or can fix.
      // `lib/openzeppelin-contracts` and `contracts/lib` are dependency checkouts (one tracked
      // entry each); the envio directories are regenerated by the indexer's codegen.
      'lib/openzeppelin-contracts/**',
      'contracts/lib/**',
      'empowertours-envio/generated/**',
      'empowertours-envio/build/**',
    ],
  },
  ...compat.extends('plugin:@next/next/recommended'),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        _N_E: 'readonly',
        MSApp: 'readonly',
        msCrypto: 'readonly',
        React: 'readonly',
        BufferSource: 'readonly',
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-expressions': 'off',
      'no-prototype-builtins': 'off',
      'no-fallthrough': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        }
      ],
      'no-cond-assign': 'warn',
      'no-empty': 'warn',
      'no-sparse-arrays': 'off',
      'no-control-regex': 'warn',
      'no-misleading-character-class': 'warn',
      'no-useless-escape': 'warn',
      'getter-return': 'warn',
      '@typescript-eslint/no-this-alias': 'off',
      'no-func-assign': 'warn',
      'no-redeclare': 'warn',
      'valid-typeof': 'warn',
      // `no-undef` stays on for plain JS, but is switched off for TypeScript below.
      'no-undef': 'error',
      '@next/next/no-img-element': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },
  {
    // TypeScript resolves ambient types the core `no-undef` rule cannot see, so the rule only
    // ever produced false positives here: `NodeJS.Timeout`, `GeolocationPosition` and
    // `GeolocationPositionError` are all real, and `tsc` already fails on a genuinely undefined
    // name. typescript-eslint's own guidance is to turn it off on TS files rather than list
    // globals one at a time.
    files: ['**/*.ts', '**/*.tsx'],
    rules: { 'no-undef': 'off' },
  },
);
