[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
solc_version = "0.8.20"
test = "test"
script = "script"
auto_detect_remappings = true
gas_snapshot_emit = true
ignored_error_codes = ["license", "code-size", "init-code-size", "transient-storage"]

[etherscan.monadTestnet]
key = "FQSX86QUTQYPUNG1WJTYBNC665XPTRYD6J"
url = "https://api-testnet.monadscan.com/api"
chain = 10143

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "forge-std=lib/forge-std/src/"
]
