export const countryData: Record<string, { name: string; symbol: string }> = {
  AF: { name: "Afghanistan", symbol: "Lion" },
  AL: { name: "Albania", symbol: "Double-headed eagle" },
  DZ: { name: "Algeria", symbol: "Fennec fox" },
  AD: { name: "Andorra", symbol: "Cow and bear" },
  AO: { name: "Angola", symbol: "Giant black sable antelope" },
  AI: { name: "Anguilla", symbol: "Dolphin" },
  AG: { name: "Antigua and Barbuda", symbol: "Pineapple" },
  AR: { name: "Argentina", symbol: "Sun of May" },
  AM: { name: "Armenia", symbol: "Mount Ararat" },
  AW: { name: "Aruba", symbol: "Divi-divi tree" },
  AU: { name: "Australia", symbol: "Kangaroo" },
  AT: { name: "Austria", symbol: "Golden eagle" },
  AZ: { name: "Azerbaijan", symbol: "Flames of fire" },
  BS: { name: "Bahamas", symbol: "Blue marlin" },
  BH: { name: "Bahrain", symbol: "Pearl monument" },
  BD: { name: "Bangladesh", symbol: "Bengal tiger" },
  BB: { name: "Barbados", symbol: "Neptune's trident" },
  BY: { name: "Belarus", symbol: "Mounted knight (Pahonia)" },
  BE: { name: "Belgium", symbol: "Lion" },
  BZ: { name: "Belize", symbol: "Baird's tapir" },
  BJ: { name: "Benin", symbol: "Leopard" },
  BM: { name: "Bermuda", symbol: "Red lion" },
  BT: { name: "Bhutan", symbol: "Thunder dragon (Druk)" },
  BO: { name: "Bolivia", symbol: "Llama" },
  BA: { name: "Bosnia and Herzegovina", symbol: "Golden lily" },
  BW: { name: "Botswana", symbol: "Zebra" },
  BR: { name: "Brazil", symbol: "Southern Cross constellation" },
  VG: { name: "British Virgin Islands", symbol: "Sage plant" },
  BN: { name: "Brunei", symbol: "Royal umbrella" },
  BG: { name: "Bulgaria", symbol: "Lion" },
  BF: { name: "Burkina Faso", symbol: "White stallion" },
  BI: { name: "Burundi", symbol: "Lion" },
  CV: { name: "Cabo Verde", symbol: "Ten stars" },
  KH: { name: "Cambodia", symbol: "Angkor Wat temple" },
  CM: { name: "Cameroon", symbol: "Lion" },
  CA: { name: "Canada", symbol: "Maple leaf" },
  KY: { name: "Cayman Islands", symbol: "Turtle" },
  CF: { name: "Central African Republic", symbol: "Elephant" },
  TD: { name: "Chad", symbol: "Goat" },
  CL: { name: "Chile", symbol: "Huemul (mountain deer)" },
  CN: { name: "China", symbol: "Dragon" },
  CX: { name: "Christmas Island", symbol: "Golden bosun bird" },
  CC: { name: "Cocos (Keeling) Islands", symbol: "Palm tree" },
  CO: { name: "Colombia", symbol: "Andean condor" },
  KM: { name: "Comoros", symbol: "Four stars and crescent" },
  CD: { name: "Congo, Democratic Republic of the", symbol: "Leopard" },
  CG: { name: "Congo, Republic of the", symbol: "Lion" },
  CK: { name: "Cook Islands", symbol: "15 stars" },
  CR: { name: "Costa Rica", symbol: "Clay-colored robin" },
  CI: { name: "Cote d'Ivoire", symbol: "Elephant" },
  HR: { name: "Croatia", symbol: "Red-white checkerboard" },
  CU: { name: "Cuba", symbol: "Royal palm" },
  CW: { name: "Curacao", symbol: "Cactus" },
  CY: { name: "Cyprus", symbol: "White dove" },
  CZ: { name: "Czechia", symbol: "Double-tailed lion" },
  DK: { name: "Denmark", symbol: "Lion" },
  DJ: { name: "Djibouti", symbol: "Red star" },
  DM: { name: "Dominica", symbol: "Sisserou parrot" },
  DO: { name: "Dominican Republic", symbol: "Palmchat (bird)" },
  EC: { name: "Ecuador", symbol: "Andean condor" },
  EG: { name: "Egypt", symbol: "Golden eagle" },
  SV: { name: "El Salvador", symbol: "Turquoise-browed motmot (bird)" },
  GQ: { name: "Equatorial Guinea", symbol: "Silk cotton tree" },
  ER: { name: "Eritrea", symbol: "Camel" },
  EE: { name: "Estonia", symbol: "Barn swallow" },
  SZ: { name: "Eswatini", symbol: "Lion" },
  ET: { name: "Ethiopia", symbol: "Abyssinian lion" },
  FK: { name: "Falkland Islands", symbol: "Ram" },
  FO: { name: "Faroe Islands", symbol: "Ram" },
  FJ: { name: "Fiji", symbol: "White dove" },
  FI: { name: "Finland", symbol: "Lion" },
  FR: { name: "France", symbol: "Gallic rooster" },
  PF: { name: "French Polynesia", symbol: "Outrigger canoe" },
  GA: { name: "Gabon", symbol: "Black panther" },
  GM: { name: "Gambia", symbol: "Lion" },
  GE: { name: "Georgia", symbol: "Saint George" },
  DE: { name: "Germany", symbol: "Eagle" },
  GH: { name: "Ghana", symbol: "Black star" },
  GI: { name: "Gibraltar", symbol: "Barbary macaque" },
  GR: { name: "Greece", symbol: "Phoenix" },
  GL: { name: "Greenland", symbol: "Polar bear" },
  GD: { name: "Grenada", symbol: "Grenada dove" },
  GU: { name: "Guam", symbol: "Coconut tree" },
  GT: { name: "Guatemala", symbol: "Quetzal (bird)" },
  GG: { name: "Guernsey", symbol: "Guernsey cow" },
  GN: { name: "Guinea", symbol: "Nimba (mask)" },
  GW: { name: "Guinea-Bissau", symbol: "Black star" },
  GY: { name: "Guyana", symbol: "Canje pheasant" },
  HT: { name: "Haiti", symbol: "Hispaniolan trogon (bird)" },
  HN: { name: "Honduras", symbol: "White-tailed deer" },
  HK: { name: "Hong Kong", symbol: "Bauhinia flower" },
  HU: { name: "Hungary", symbol: "Turul (mythical bird)" },
  IS: { name: "Iceland", symbol: "Gyrfalcon" },
  IN: { name: "India", symbol: "Lion Capital of Ashoka" },
  ID: { name: "Indonesia", symbol: "Garuda (mythical bird)" },
  IR: { name: "Iran", symbol: "Lion and sun" },
  IQ: { name: "Iraq", symbol: "Golden eagle" },
  IE: { name: "Ireland", symbol: "Harp" },
  IM: { name: "Isle of Man", symbol: "Triskelion" },
  IL: { name: "Israel", symbol: "Star of David" },
  IT: { name: "Italy", symbol: "Stella d'Italia (Star of Italy)" },
  JM: { name: "Jamaica", symbol: "Green-and-black streamertail (bird)" },
  JP: { name: "Japan", symbol: "Cherry blossom" },
  JE: { name: "Jersey", symbol: "Jersey cow" },
  JO: { name: "Jordan", symbol: "Eagle" },
  KZ: { name: "Kazakhstan", symbol: "Golden eagle" },
  KE: { name: "Kenya", symbol: "Lion" },
  KI: { name: "Kiribati", symbol: "Frigate bird" },
  KP: { name: "Korea, North", symbol: "Red star" },
  KR: { name: "Korea, South", symbol: "Taeguk (yin-yang symbol)" },
  XK: { name: "Kosovo", symbol: "Six stars" },
  KW: { name: "Kuwait", symbol: "Falcon" },
  KG: { name: "Kyrgyzstan", symbol: "Falcon" },
  LA: { name: "Laos", symbol: "Elephant" },
  LV: { name: "Latvia", symbol: "Freedom Monument" },
  LB: { name: "Lebanon", symbol: "Cedar tree" },
  LS: { name: "Lesotho", symbol: "Mokorotlo (hat)" },
  LR: { name: "Liberia", symbol: "White star" },
  LY: { name: "Libya", symbol: "Star and crescent" },
  LI: { name: "Liechtenstein", symbol: "Princely hat" },
  LT: { name: "Lithuania", symbol: "Vytis (knight on horseback)" },
  LU: { name: "Luxembourg", symbol: "Lion" },
  MO: { name: "Macau", symbol: "Lotus flower" },
  MG: { name: "Madagascar", symbol: "Traveller's palm" },
  MW: { name: "Malawi", symbol: "Rising sun" },
  MY: { name: "Malaysia", symbol: "Tiger" },
  MV: { name: "Maldives", symbol: "Coconut palm" },
  ML: { name: "Mali", symbol: "Great Mosque of Djenne" },
  MT: { name: "Malta", symbol: "Maltese cross" },
  MH: { name: "Marshall Islands", symbol: "24-rayed sun" },
  MR: { name: "Mauritania", symbol: "Star and crescent" },
  MU: { name: "Mauritius", symbol: "Dodo bird" },
  MX: { name: "Mexico", symbol: "Golden eagle" },
  FM: { name: "Micronesia", symbol: "Stars and stripes (4 stars)" },
  MD: { name: "Moldova", symbol: "Aurochs (bison)" },
  MC: { name: "Monaco", symbol: "Coat of arms with lozenge pattern" },
  MN: { name: "Mongolia", symbol: "Soyombo symbol" },
  ME: { name: "Montenegro", symbol: "Double-headed eagle" },
  MS: { name: "Montserrat", symbol: "Lady with harp" },
  MA: { name: "Morocco", symbol: "Pentacle symbol" },
  MZ: { name: "Mozambique", symbol: "AK-47 rifle" },
  MM: { name: "Myanmar", symbol: "Chinthe (mythical lion)" },
  NA: { name: "Namibia", symbol: "Welwitschia plant" },
  NR: { name: "Nauru", symbol: "Frigate bird" },
  NP: { name: "Nepal", symbol: "Rhododendron" },
  NL: { name: "Netherlands", symbol: "Lion" },
  NC: { name: "New Caledonia", symbol: "Flèche faîtière (roof spire)" },
  NZ: { name: "New Zealand", symbol: "Kiwi bird" },
  NI: { name: "Nicaragua", symbol: "Triangle with rainbow" },
  NE: { name: "Niger", symbol: "Zebu (cow)" },
  NG: { name: "Nigeria", symbol: "Eagle" },
  NU: { name: "Niue", symbol: "Yellow star" },
  NF: { name: "Norfolk Island", symbol: "Norfolk Island pine" },
  MK: { name: "North Macedonia", symbol: "Eight-rayed sun" },
  MP: { name: "Northern Mariana Islands", symbol: "Latte stone" },
  NO: { name: "Norway", symbol: "Lion" },
  OM: { name: "Oman", symbol: "Khanjar dagger" },
  PK: { name: "Pakistan", symbol: "Crescent and star" },
  PW: { name: "Palau", symbol: "Bai (traditional meeting house)" },
  PS: { name: 'Palestine', symbol: 'Eagle of Saladin' },
  PA: { name: 'Panama', symbol: 'Harpy eagle' },
  PG: { name: 'Papua New Guinea', symbol: 'Bird of paradise' },
  PY: { name: 'Paraguay', symbol: 'Star of May' },
  PE: { name: 'Peru', symbol: 'Vicuña (alpaca-like animal)' },
  PH: { name: 'Philippines', symbol: 'Three stars and sun' },
  PN: { name: 'Pitcairn Islands', symbol: 'Pitcairn wheelbarrow' },
  PL: { name: 'Poland', symbol: 'White eagle' },
  PT: { name: 'Portugal', symbol: 'Armillary sphere' },
  PR: { name: 'Puerto Rico', symbol: 'Coquí frog' },
  QA: { name: 'Qatar', symbol: 'Oryx' },
  RO: { name: 'Romania', symbol: 'Eagle' },
  RU: { name: 'Russia', symbol: 'Double-headed eagle' },
  RW: { name: 'Rwanda', symbol: 'Traditional hut' },
  BL: { name: 'Saint Barthelemy', symbol: 'Fleur-de-lis' },
  SH: { name: 'Saint Helena', symbol: 'Wirebird' },
  KN: { name: 'Saint Kitts and Nevis', symbol: 'Pelican' },
  LC: { name: 'Saint Lucia', symbol: 'Twin pitons (mountains)' },
  MF: { name: 'Saint Martin', symbol: 'Pelican' },
  PM: { name: 'Saint Pierre and Miquelon', symbol: '16th-century sailing ship' },
  VC: { name: 'Saint Vincent and the Grenadines', symbol: 'Breadfruit' },
  WS: { name: 'Samoa', symbol: 'Southern Cross constellation' },
  SM: { name: 'San Marino', symbol: 'Three towers' },
  ST: { name: 'Sao Tome and Principe', symbol: 'Cocoa pod' },
  SA: { name: 'Saudi Arabia', symbol: 'Palm tree and crossed swords' },
  SN: { name: 'Senegal', symbol: 'Lion' },
  RS: { name: 'Serbia', symbol: 'Double-headed eagle' },
  SC: { name: 'Seychelles', symbol: 'Coco de mer' },
  SL: { name: 'Sierra Leone', symbol: 'Lion' },
  SG: { name: 'Singapore', symbol: 'Lion' },
  SX: { name: 'Sint Maarten', symbol: 'Pelican' },
  SK: { name: 'Slovakia', symbol: 'Double cross' },
  SI: { name: 'Slovenia', symbol: 'Mount Triglav' },
  SB: { name: 'Solomon Islands', symbol: 'Eagle' },
  SO: { name: 'Somalia', symbol: 'Leopard' },
  ZA: { name: 'South Africa', symbol: 'Protea flower' },
  SS: { name: 'South Sudan', symbol: 'African fish eagle' },
  ES: { name: 'Spain', symbol: 'Pillars of Hercules' },
  LK: { name: 'Sri Lanka', symbol: 'Lion' },
  SD: { name: 'Sudan', symbol: 'Secretary bird' },
  SR: { name: 'Suriname', symbol: 'Royal palm' },
  SE: { name: 'Sweden', symbol: 'Three crowns' },
  CH: { name: 'Switzerland', symbol: 'Swiss cross' },
  SY: { name: 'Syria', symbol: 'Hawk of Quraish' },
  TW: { name: 'Taiwan', symbol: 'Blue sky with white sun' },
  TJ: { name: 'Tajikistan', symbol: 'Crown with seven stars' },
  TZ: { name: 'Tanzania', symbol: 'Uhuru torch' },
  TH: { name: 'Thailand', symbol: 'Garuda' },
  TL: { name: 'Timor-Leste', symbol: 'Mount Ramelau' },
  TG: { name: 'Togo', symbol: 'Lion' },
  TK: { name: 'Tokelau', symbol: 'Tuluma (fishing box)' },
  TO: { name: 'Tonga', symbol: 'Three stars' },
  TT: { name: 'Trinidad and Tobago', symbol: 'Scarlet ibis (bird)' },
  TN: { name: 'Tunisia', symbol: 'Encirled star and crescent' },
  TR: { name: 'Turkey', symbol: 'Crescent and star' },
  TM: { name: 'Turkmenistan', symbol: 'Akhal-Teke horse' },
  TC: { name: 'Turks and Caicos Islands', symbol: 'Conch shell' },
  TV: { name: 'Tuvalu', symbol: 'Maneapa (meeting house)' },
  UG: { name: 'Uganda', symbol: 'Grey crowned crane' },
  UA: { name: 'Ukraine', symbol: 'Tryzub (trident)' },
  AE: { name: 'United Arab Emirates', symbol: 'Golden falcon' },
  GB: { name: 'United Kingdom', symbol: 'Lion' },
  US: { name: 'United States', symbol: 'Bald eagle' },
  UY: { name: 'Uruguay', symbol: 'Sun of May' },
  UZ: { name: 'Uzbekistan', symbol: 'Khumo (mythical bird)' },
  VU: { name: "Vanuatu", symbol: "Boar's tusk" },
  VA: { name: 'Vatican City', symbol: 'Crossed keys' },
  VE: { name: 'Venezuela', symbol: 'Trouvial (bird)' },
  VN: { name: 'Vietnam', symbol: 'Dragon and fairy' },
  VI: { name: 'Virgin Islands', symbol: 'Bananaquit (bird)' },
  WF: { name: 'Wallis and Futuna', symbol: 'Unofficial flag with French symbols' },
  YE: { name: 'Yemen', symbol: 'Golden eagle' },
  ZM: { name: 'Zambia', symbol: 'African fish eagle' },
  ZW: { name: 'Zimbabwe', symbol: 'Zimbabwe bird' },
};
