[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 1
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${MONAD_SCAN_API_KEY}", url = "https://testnet.monadscan.com/api" }
