export interface WeekCurriculum {
  week: number;
  title: string;
  description: string;
  requiredFiles: string[];
  phase: number;
  phaseColor: string;
  phaseName: string;
  isMilestone: boolean;
}

export const CURRICULUM: WeekCurriculum[] = [
  // Phase 1: Dev Foundations (Weeks 1-8) — #06b6d4
  {
    week: 1,
    title: 'GitHub Account & Profile Setup',
    description: 'Set up your GitHub profile with bio, avatar, and pinned repos.',
    requiredFiles: ['week-01/profile.md'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 2,
    title: 'WSL & Terminal Basics',
    description: 'Install WSL, learn basic terminal commands (ls, cd, mkdir, etc).',
    requiredFiles: ['week-02/commands.md'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 3,
    title: 'Git Fundamentals',
    description: 'Learn git init, add, commit, push, pull. Create a repo with 3+ commits.',
    requiredFiles: ['week-03/first-repo.md'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 4,
    title: 'Secrets, .gitignore & Privacy',
    description: 'Learn .gitignore patterns, .env.example pattern, secret rotation, and what happens when secrets leak.',
    requiredFiles: ['week-04/gitignore-demo/.gitignore', 'week-04/security-checklist.md'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 5,
    title: 'Branching, Merging & PRs',
    description: 'Create branches, merge them, and open pull requests for code review.',
    requiredFiles: ['week-05/pr-review.md'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 6,
    title: 'Pre-commits & Secrets Scanning',
    description: 'Set up pre-commit hooks with detect-secrets and gitleaks to prevent accidental secret commits.',
    requiredFiles: ['week-06/.pre-commit-config.yaml'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 7,
    title: 'CI/CD & GitHub Actions',
    description: 'Create a GitHub Actions workflow for continuous integration.',
    requiredFiles: ['week-07/.github/workflows/ci.yml'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: false,
  },
  {
    week: 8,
    title: 'HTML/CSS/JS Basics',
    description: 'Build a basic web page with valid HTML, CSS styling, and JavaScript interactivity.',
    requiredFiles: ['week-08/index.html'],
    phase: 1,
    phaseColor: '#06b6d4',
    phaseName: 'Dev Foundations',
    isMilestone: true,
  },
  // Phase 2: Web3 & Blockchain (Weeks 9-20) — #8b5cf6
  {
    week: 9,
    title: 'What is Blockchain?',
    description: 'Write a 300+ word essay explaining blockchain technology, consensus, and decentralization.',
    requiredFiles: ['week-09/blockchain-essay.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 10,
    title: 'Wallet Security & Key Management',
    description: 'Document private key storage best practices, hardware wallets, burner wallets, and why you never commit mnemonics.',
    requiredFiles: ['week-10/key-safety.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 11,
    title: 'Wallets & Transactions on Monad',
    description: 'Set up a wallet and send a transaction on Monad. Document the tx hash.',
    requiredFiles: ['week-11/wallet-setup.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 12,
    title: 'Foundry Setup & Solidity Basics',
    description: 'Install Foundry, create a project with foundry.toml, write a Storage contract with events, modifiers, and Ownable.',
    requiredFiles: ['week-12/foundry.toml', 'week-12/src/Storage.sol'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 13,
    title: 'ERC-20 Token with Foundry',
    description: 'Write an ERC-20 token contract with OpenZeppelin and Foundry tests.',
    requiredFiles: ['week-13/src/MyToken.sol', 'week-13/test/MyToken.t.sol'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 14,
    title: 'Deploying on Monad (Testnet & Mainnet)',
    description: 'Deploy your token on both testnet and mainnet. Verify on MonadScan. Document addresses and links.',
    requiredFiles: ['week-14/deployment.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 15,
    title: 'Reading Contracts with viem',
    description: 'Use viem to read data from your deployed contract (balanceOf, totalSupply, etc).',
    requiredFiles: ['week-15/read-contract.ts'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 16,
    title: 'Writing Transactions with viem',
    description: 'Use viem to send a write transaction to your deployed contract.',
    requiredFiles: ['week-16/send-tx.ts'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 17,
    title: 'NFT Fundamentals (ERC-721) with Foundry',
    description: 'Write an ERC-721 NFT contract and Foundry tests.',
    requiredFiles: ['week-17/src/MyNFT.sol', 'week-17/test/MyNFT.t.sol'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 18,
    title: 'On-chain SVG NFTs',
    description: 'Create an NFT contract that generates SVG art on-chain. Deploy and verify on Monad.',
    requiredFiles: ['week-18/src/OnChainNFT.sol'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 19,
    title: 'DeFi Concepts',
    description: 'Write a 400+ word summary of DeFi concepts: AMMs, lending, yield farming, liquidity pools.',
    requiredFiles: ['week-19/defi-summary.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: false,
  },
  {
    week: 20,
    title: 'Smart Contract Security & Auditing',
    description: 'Audit a smart contract. Document vulnerabilities, severity, and recommendations.',
    requiredFiles: ['week-20/AuditReport.md'],
    phase: 2,
    phaseColor: '#8b5cf6',
    phaseName: 'Web3 & Blockchain',
    isMilestone: true,
  },
  // Phase 3: Full-Stack Development (Weeks 21-36) — #f59e0b
  {
    week: 21,
    title: 'React Fundamentals',
    description: 'Build a React app with components, state, and props.',
    requiredFiles: ['week-21/src/App.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 22,
    title: 'Next.js Getting Started',
    description: 'Create a Next.js app with App Router, pages, and layouts.',
    requiredFiles: ['week-22/app/page.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 23,
    title: 'Tailwind CSS & Responsive Design',
    description: 'Style your app with Tailwind CSS and make it fully responsive.',
    requiredFiles: ['week-23/app/globals.css'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 24,
    title: 'API Routes & Server Actions',
    description: 'Create Next.js API routes for server-side data handling.',
    requiredFiles: ['week-24/app/api/data/route.ts'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 25,
    title: 'Database Basics (Redis)',
    description: 'Use Upstash Redis for caching and data storage in your API routes.',
    requiredFiles: ['week-25/app/api/redis-demo/route.ts'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 26,
    title: 'Authentication with Privy',
    description: 'Add Privy authentication to your Next.js app for wallet + social login.',
    requiredFiles: ['week-26/components/providers.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 27,
    title: 'Frontend ↔ Smart Contracts',
    description: 'Connect your frontend to smart contracts using viem for reads and writes.',
    requiredFiles: ['week-27/app/page.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 28,
    title: 'Full-Stack dApp: Token Dashboard',
    description: 'Build a complete token dashboard showing balances, transfers, and history.',
    requiredFiles: ['week-28/README.md'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 29,
    title: 'Testing Basics',
    description: 'Write unit and integration tests for your components and API routes.',
    requiredFiles: ['week-29/tests/'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 30,
    title: 'Deployment (Railway/Vercel)',
    description: 'Deploy your dApp to Railway or Vercel. Document the live URL.',
    requiredFiles: ['week-30/deployment.md'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 31,
    title: 'TypeScript Deep Dive',
    description: 'Master advanced TypeScript: generics, utility types, type guards, and discriminated unions.',
    requiredFiles: ['week-31/src/types.ts'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 32,
    title: 'Form Handling & Validation',
    description: 'Build forms with proper validation, error handling, and UX feedback.',
    requiredFiles: ['week-32/app/form/page.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 33,
    title: 'File Uploads & IPFS',
    description: 'Implement file uploads and store files on IPFS via Pinata or similar.',
    requiredFiles: ['week-33/app/api/upload/route.ts'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 34,
    title: 'Webhooks & Event Processing',
    description: 'Build a webhook handler that processes external events and updates state.',
    requiredFiles: ['week-34/app/api/webhook/route.ts'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 35,
    title: 'Performance & Optimization',
    description: 'Add loading states, error boundaries, and optimize your app performance.',
    requiredFiles: ['week-35/app/loading.tsx', 'week-35/app/error.tsx'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: false,
  },
  {
    week: 36,
    title: 'Capstone: Mini dApp',
    description: 'Build and deploy a complete mini dApp combining everything you learned.',
    requiredFiles: ['week-36/README.md'],
    phase: 3,
    phaseColor: '#f59e0b',
    phaseName: 'Full-Stack Development',
    isMilestone: true,
  },
  // Phase 4: Business & Startup (Weeks 37-52) — #22c55e
  {
    week: 37,
    title: 'Problem Discovery & Validation',
    description: 'Identify a real problem, interview potential users, and validate the opportunity.',
    requiredFiles: ['week-37/problem-validation.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 38,
    title: 'Business Model Canvas',
    description: 'Create a business model canvas for your startup idea.',
    requiredFiles: ['week-38/business-model-canvas.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 39,
    title: 'Competitive Analysis',
    description: 'Research competitors and document your competitive advantage.',
    requiredFiles: ['week-39/competitive-analysis.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 40,
    title: 'User Personas & Journey Maps',
    description: 'Create detailed user personas and map their journey through your product.',
    requiredFiles: ['week-40/user-personas.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 41,
    title: 'MVP Definition & Roadmap',
    description: 'Define your minimum viable product and create a development roadmap.',
    requiredFiles: ['week-41/mvp-roadmap.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 42,
    title: 'Tokenomics Design',
    description: 'Design token economics: supply, distribution, utility, and incentive mechanisms.',
    requiredFiles: ['week-42/tokenomics.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 43,
    title: 'Marketing Strategy for Web3',
    description: 'Create a Web3 marketing plan covering community, content, and growth strategies.',
    requiredFiles: ['week-43/marketing-plan.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 44,
    title: 'Community Building',
    description: 'Build and grow a community around your project using Discord, Twitter, and Farcaster.',
    requiredFiles: ['week-44/community-report.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 45,
    title: 'Financial Projections',
    description: 'Create financial projections for your startup: revenue model, costs, and runway.',
    requiredFiles: ['week-45/financial-model.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 46,
    title: 'Pitch Deck Draft',
    description: 'Create a compelling pitch deck for your startup.',
    requiredFiles: ['week-46/pitch-deck.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 47,
    title: 'Legal & Compliance Basics',
    description: 'Research legal requirements, compliance, and regulatory considerations for your Web3 startup.',
    requiredFiles: ['week-47/legal-overview.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 48,
    title: 'Fundraising Strategy',
    description: 'Create a fundraising plan: target investors, round structure, and use of funds.',
    requiredFiles: ['week-48/fundraising-plan.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 49,
    title: 'Demo Day Rehearsal',
    description: 'Record a demo video of your product and pitch. Share the link.',
    requiredFiles: ['week-49/demo-video-link.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 50,
    title: 'NITRO Application Prep',
    description: 'Prepare your NITRO accelerator application with all required materials.',
    requiredFiles: ['week-50/nitro-application-draft.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 51,
    title: 'LATAM Market Deep Dive',
    description: 'Research and analyze the LATAM market for your product: regulations, competition, and opportunities.',
    requiredFiles: ['week-51/latam-market-analysis.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: false,
  },
  {
    week: 52,
    title: 'Final Presentation & Graduation',
    description: 'Present your complete project and graduate from TURBO Cohort 1.',
    requiredFiles: ['week-52/graduation.md'],
    phase: 4,
    phaseColor: '#22c55e',
    phaseName: 'Business & Startup',
    isMilestone: true,
  },
];

export const PHASES = [
  { phase: 1, name: 'Dev Foundations', color: '#06b6d4', weeks: '1-8' },
  { phase: 2, name: 'Web3 & Blockchain', color: '#8b5cf6', weeks: '9-20' },
  { phase: 3, name: 'Full-Stack Development', color: '#f59e0b', weeks: '21-36' },
  { phase: 4, name: 'Business & Startup', color: '#22c55e', weeks: '37-52' },
];

export const MILESTONE_WEEKS = [8, 20, 36, 52];

export function getWeekCurriculum(week: number): WeekCurriculum | undefined {
  return CURRICULUM.find(c => c.week === week);
}

export function getPhaseForWeek(week: number): number {
  if (week <= 8) return 1;
  if (week <= 20) return 2;
  if (week <= 36) return 3;
  return 4;
}
