[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
monadTestnet = "${MONAD_TESTNET_RPC_URL}"

[etherscan]
monadTestnet = { key = "${MONAD_TESTNET_EXPLORER_API_KEY}", url = "https://testnet.monadscan.com/api" }
